insert into COUNTRY_MASTER values(2,'+1','USA');
insert into COUNTRY_MASTER values(1,'+91','India');
insert into STATE_MASTER values(1,1,'Telangana');
insert into STATE_MASTER values(3,2,'New York');
insert into STATE_MASTER values(4,2,'New Jersey');
insert into STATE_MASTER values(2,1,'AndraPradesh');
insert into CITY_MASTER values(1,'Amaravathi',2);
insert into CITY_MASTER values(2,'Vizag',2);
insert into CITY_MASTER values(3,'Karimnagar',1);
insert into CITY_MASTER values(4,'WARANGAL',1);
insert into CITY_MASTER values(5,'Hyderabad',1);
insert into CITY_MASTER values(6,'Amsterdam',1);
insert into CITY_MASTER values(7,'Buffalo',1);
insert into CITY_MASTER values(8,'Jersey',2);
insert into CITY_MASTER values(9,'WildWood',2);
